#Name
#trigger
#jobs
  #steps

name : React CI

on : push

jobs : 
  run-test:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      
      - name: Use Node.js
        uses: actions/setup-node@v4

        with:
          node-version: '18'
    
    run-build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: npm install
        
        - name: Use Node.js
          uses: actions/setup-node@v4

          with:
            node-version: '18'

        - name: Build Project
          run: npm run build